version: '3.8'
services:
  mongo:
    image: mirror.gcr.io/library/mongo:8
    platform: linux/amd64
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin_user
      MONGO_INITDB_ROOT_PASSWORD: web3
    ports:
      - "27017:27017"
    networks:
      - mongo-network

  calculadora:
    # USAR: ghcr.io/[usuario_minÃºsculas]/[repo_minÃºsculas]:latest-backend
    image: ghcr.io/adriantinal/practica-web:latest-backend 

    pull_policy: always
    # AÃ‘ADIDO: Forzar la arquitectura a Linux/AMD64 para asegurar compatibilidad con el runner de GitHub
    platform: linux/amd64 
    ports:
      - "8000:8000"
    networks:
      - mongo-network
    depends_on:
      - mongo

  frontend:
    # USAR: ghcr.io/[usuario_minÃºsculas]/[repo_minÃºsculas]:latest-frontend
    image: ghcr.io/adriantinal/practica-web:latest-frontend 
    # AÃ‘ADIDO: Forzar la arquitectura a Linux/AMD64 para asegurar compatibilidad con el runner de GitHub
    platform: linux/amd64
    ports:
      # Puerto del contenedor: Puerto local
      - "3000:3000" 
    
    environment:
      # ðŸš€ INDICA al servidor de desarrollo de React que use el proxy.
      # El nombre 'calculadora' es el nombre del servicio Docker.
      # Si usas Create React App (CRA), esta variable debe ser 'PROXY=http://calculadora:8000'
      PROXY: http://calculadora:8000
      
    depends_on:
      - calculadora
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge
